spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_base
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
custom-properties:
  jwt:
    secret: jsonwebtokensecretphrasepneumonoultramicroscopicsilicovolcanoconiosisantidisestablishmentarianism
    issuer: ilya